"""add last_check_in_at to user

Revision ID: f3ec065f686c
Revises: 0f6643ed11d2
Create Date: 2026-06-11 18:51:42.443588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ec065f686c'
down_revision: Union[str, Sequence[str], None] = '0f6643ed11d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_check_in_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_check_in_at')
    # ### end Alembic commands ###
